HP-729 study-details component created
hariduspilv/haridusportaal pull request #1451
Opened 2021-04-15 08:35 UTC by mitka0260

Please review my code test component creating

2021-04-22 15:31 UTC, mitka0260 commented
please review my first code in TWN

2021-04-23 12:30 UTC, madispold requested changes
Back to you :)

2021-04-23 12:30 UTC, madispold commented on angular-fe/src/app/_core/models/interfaces/main.ts
> +}
This is a general interface usable globally, should remove study module reference from name.

2021-04-23 12:30 UTC, madispold commented on angular-fe/src/app/modules/study/containers/study-detail/study-detail.component.ts
> +			tap(() => this.loading = false, error => console.log('Error: ', error)),
No actual error handling takes place, should make a global interceptor to direct to 404 page if response route === null.

2021-04-23 12:30 UTC, madispold commented on angular-fe/src/app/_services/SettingsService.ts
> +	}
Need to use similar indenting configuration in IDEs. Project has been developed using:
**Indent using tabs, tab size 2.**

2021-04-23 12:30 UTC, madispold commented on drupal/web/modules/custom/htm_custom_querymap_form/Maps/raw/studyListViewQuery.graphql
> +  nodeQuery(offset: $offset, limit: $limit, sort: {field: $sortField, direc`tion: $sortDirection, language: $lang},
This is a typo -> should check commits file-by-file in the future to find these

2021-04-23 12:30 UTC, madispold commented on angular-fe/src/app/modules/study/containers/study-detail/study-detail.component.scss
> +}
Nice BEM pattern, but this style has no use in the template, is redundant.

2021-04-23 12:30 UTC, madispold commented on angular-fe/src/app/modules/study/containers/study-detail/study-detail.component.html
> +					<strong>{{study.fieldIntroduction.substring(0, 300)}}</strong>
Should be handled by BE, this limit is not for angular to handle. Also, should never use function calls in templates :)

2021-04-23 12:30 UTC, madispold commented on angular-fe/src/app/modules/study/containers/study-detail/study-detail.component.html
> +					class="study__list__item__labels"
Misleading class name and this particular class serves no purpose (no styles reference it), every bit of extra code should be removed if possible

2021-04-23 12:30 UTC, madispold commented on angular-fe/src/app/modules/study/containers/study-detail/study-detail.component.html
> +					<strong>{{study.fieldIntroduction.substring(0, 300)}}</strong>
Also, strong tag somehow adds font-weight of 700, the designs require 500.

2021-04-23 12:30 UTC, madispold commented on angular-fe/src/app/modules/study/containers/study-detail/study-detail.component.html
> +				<p style="font-weight: 500">{{ 'study.reference_title' | translate }}:</p>
Should never write inline css styles (if possible), include in .scss file for uniform styles and 1 source of truth.

2021-04-23 12:39 UTC, madispold commented on angular-fe/src/app/modules/study/containers/study-detail/study-detail.component.ts
> +			tap(() => this.loading = false, error => console.log('Error: ', error)),
I will make the interceptor myself actually, then we can review it together later

2021-04-26 07:08 UTC, mitka0260 commented on angular-fe/src/app/_core/models/interfaces/main.ts
> +}
corrected to ImageEntity

2021-04-26 07:09 UTC, mitka0260 commented on angular-fe/src/app/_services/SettingsService.ts
> +	}
file .editorconfig in the root of the project should regulate these configurations

2021-04-26 07:10 UTC, mitka0260 commented on angular-fe/src/app/modules/study/containers/study-detail/study-detail.component.scss
> +}
deleted, and was added class "bold"

2021-04-26 07:10 UTC, mitka0260 commented on angular-fe/src/app/modules/study/containers/study-detail/study-detail.component.html
> +					class="study__list__item__labels"
extra code was removed

2021-04-26 07:20 UTC, merged