HP-526 | field_defaults moodul
hariduspilv/haridusportaal pull request #1528
Opened 2021-06-03 07:36 UTC by andresly

2021-06-03 07:52 UTC, voldemar-p commented
Hetkel tekib seoses HP-864-ga (Drupali turvauuendus) composeris konflikt, kuna praegusel juhul oleks 2 erinevat paralleelset composer.lock muudatust.
Võimalus on näiteks HP-526 PR teha hiljem, juba uuenenud master harult (master uuendatakse täna, 03.06), kus sees on ka eelmine composer muudatusega seotud pilet (HP-864).

2021-06-03 07:53 UTC, voldemar-p requested changes
Hetkel tekib seoses HP-864-ga (Drupali turvauuendus) composeris konflikt, kuna praegusel juhul oleks 2 erinevat paralleelset composer.lock muudatust.
Võimalus on näiteks HP-526 PR teha hiljem, juba uuenenud master harult (master uuendatakse täna, 03.06), kus sees on ka eelmine composer muudatusega seotud pilet (HP-864).

2021-06-09 10:28 UTC, andresly commented
Mergesin HP-882, nüüd konflikt kadunud

2021-06-09 10:29 UTC, voldemar-p approved these changes

2021-06-09 10:29 UTC, merged